### ISSUE TITLE
Adding dimensions and measures

### ISSUE THREAD

**Issue by SarahHLamb** [ralfbecher/QlikSense_Extension_PivotMadness#2]
Hi Ralf,

I've created a pivot madness object within an app and I can see all the various options to change the appearance but there aren't any sections for Data, Sorting or Add-ons on the right hand side menu unlike other Qlik Sense objects.

How can I add dimensions and measures to the pivot table without these sections?

Thank you,

Sarah

PS here's a screenshot in case it helps:
![pivotmadness](https://user-images.githubusercontent.com/19289504/29269020-55379974-80e7-11e7-8c1d-95e15269ea48.PNG)

**Comment by SarahHLamb** [comment]
Hi Ralf,

Apologies, cancel last message, I misunderstood the Options section.

Thanks,

Saraj

**Comment by pkoripalli** [comment]
SarahHLamb

  I am having same issue, I am not able to add dimension and measures. can you please let me know the steps to add?

 I am getting below error when I add dimension.

![image](https://user-images.githubusercontent.com/35025873/34478585-b8d3deb2-efc7-11e7-832e-3615a7e727cd.png)


Thanks,
Prithvi.

**Comment by ralfbecher** [comment]
This extension has no dimension nor measure..

**Comment by pkoripalli** [comment]
Thanks for the response Ralf, how do I see the data then? can you please direct me with the steps?

**Comment by ralfbecher** [comment]
This extension has no data. It will manipulate existing pivot table objects on the sheet.

**Comment by pkoripalli** [comment]
Ok I have a qlik sense pivot table with the data, then I tried to replace that pivot table with the Pivot madness. still no luck, really not sure what I am missing though.  thanks for your quick response

**Comment by ralfbecher** [comment]
Why replace? If no pivot table exists on the sheet this extension has nothing to do..

**Comment by pkoripalli** [comment]
Do you have any documentation on usage of this extension? it would be great if you can share it.

**Comment by ralfbecher** [comment]
Yes it's the README.md
