### ISSUE TITLE
Expand Left Dims Bug?

### ISSUE THREAD

**Issue by Exojolt** [ralfbecher/QlikSense_Extension_PivotMadness#3]
Hi there! First of all, what an amazing extension. We're making good use of it! We have an issue with this extension which occurred after upgrading Qlik Sense to the June release. The function "Expand Left Dims" should expand the table by one level. However, when we use this function now it expands the entire tree. So in short, it appears that the "Expand Left Dims" have the same exact functionality as "Full Expand On".

I sincerely await your reply.

Exo

**Comment by Exojolt** [comment]
Bump?

**Comment by ralfbecher** [comment]
It works as expected now since the API bug was fixed. Before, the limitation was as you described that first dim was expanded only. To expand a certain level you can click on that level. Maybe I can add another button to expand first level only.

**Comment by ralfbecher** [comment]
fyi, I added another property to switch this behavior.
