### ISSUE TITLE
Not able to add dimension and measure

### ISSUE THREAD

**Issue by pkoripalli** [ralfbecher/QlikSense_Extension_PivotMadness#5]
Hi,

  I am not able to add dimension and measures. when I add I am getting below error, can you please add let me know if I am missing anything or can you please let me know the steps to add them ?

![image](https://user-images.githubusercontent.com/35025873/34478672-2840ce5e-efc8-11e7-8eba-5d8fd5d233fb.png)

Thanks,
Prithvi.

**Comment by ralfbecher** [comment]
This extension has no dimension nor measure..
