### ISSUE TITLE
Parameter no valid when unselect option "Expand All Levels" on "Left Dims"

### ISSUE THREAD

**Issue by cerfyxz** [ralfbecher/QlikSense_Extension_PivotMadness#6]
Hi this is the issue i speaks to you on twitter, i'am @Pandrax

![issuepivotmadness](https://user-images.githubusercontent.com/18714471/37985220-6d81392a-31b5-11e8-9ce7-f095db2d12ad.gif)

**Comment by ralfbecher** [comment]
Cannot reproduce with version Feb'18 Patch 1..

**Comment by cerfyxz** [comment]
Sorry i confusing the date, so with first patch of Feb of this year, right?


Ty and have excellent day :)

**Comment by ralfbecher** [comment]
Yes, my version is February 2018 Patch 1. So, maybe this is related to your data somehow?

**Comment by cerfyxz** [comment]
I have the February 2018 version, today i will apply the patch 1, I tell you how result

thanks for your help :)

**Comment by cerfyxz** [comment]
Hi, Ralf 

I install Feb'18 Parch 1. Unfortunately the issue has persisted. I even tried reinstalling the extension and reboot the server

**Comment by ralfbecher** [comment]
Ok, then I would need a sample app to investigate..

**Comment by cerfyxz** [comment]
Ok give me a time to prepare a lithe version, current application is so very heavy, A little question,do you use some Engine API,and so that the extension works well is it necessary to have it installed?

Thanks for your help and time

**Comment by ralfbecher** [comment]
Yes it uses engine API via enigma, which is a reference in the client. You do not need to install smth..

**Comment by cerfyxz** [comment]
Hi Ralf

I found the problem, on pivot table if you active "Show Totals"(Mostrar Totales ) the extension send a message "Invalid parameters"(Parametros no validos). If I turn off this option I can expand first level but I have made it to the first row at expanding. Could you try replicating it?

Testing File: 
[TestingMadneesPivot.zip](https://github.com/ralfbecher/QlikSense_Extension_PivotMadness/files/1871786/TestingMadneesPivot.zip)

Example gif

![issuepivotmadness2](https://user-images.githubusercontent.com/18714471/38253103-68bf54ec-371b-11e8-9213-213165f86707.gif)

**Comment by ralfbecher** [comment]
Actually, this is an error (bug) in client.js - the Qlik Sense client. Unfortunately, I can not solve this.

**Comment by cerfyxz** [comment]
Okey, then there is no other option than waiting for another patch

Thank you very much Ralf for your help and time
