### ISSUE TITLE
Left and Top  Expand/Collapse doesn´t work

### ISSUE THREAD

**Issue by sgonzalez89** [ralfbecher/QlikSense_Extension_PivotMadness#7]
In last versions this function doesn't work when you click on buttons.

**Comment by ralfbecher** [comment]
Could you give more details for your issue. Btw. the API behavior has changed in version April 2018 so that the first entry for left dim will be expanded/collapsed only. So, this is expected behavior with no other possible solution.

**Comment by sgonzalez89** [comment]
That´s what I need 
> that the first entry for left dim will be expanded/collapsed only
But in June 2018 version "Expand Left Dims" and "Collapse Left Dims" buttons don't work if  are as below. 
![image](https://user-images.githubusercontent.com/38265803/43803254-02c5ac3a-9a5e-11e8-9e45-732ff5a5d2cb.png)
 If I active "Expand All Levels" works, but I just want first entry.
Thanks for your support.

**Comment by ralfbecher** [comment]
There is no solution at the moment because there is no API call for this.
